version: "3.9"
services:
  api:
    image: 'herrdani/demo-project_server:latest'
    hostname: api
    ports:
      - '8080:8080'
  client:
    image: 'herrdani/demo-project_frontend:latest'
    hostname: client
    ports:
      - '3000:3000'